[colors.bright]
black = "0x383a42"
blue = "0x0184bc"
cyan = "0x0997b3"
green = "0x50a14f"
magenta = "0xa626a4"
red = "0xe45649"
white = "0xfafafa"
yellow = "0xc18401"

[colors.normal]
black = "0x383a42"
blue = "0x0184bc"
cyan = "0x0997b3"
green = "0x50a14f"
magenta = "0xa626a4"
red = "0xe45649"
white = "0xfafafa"
yellow = "0xc18401"

[colors.primary]
background = "0xfafafa"
foreground = "0x383a42"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[window]
option_as_alt = "Both"

[window.dimensions]
columns = 160
lines = 80
